### ISSUE TITLE
Running example.py creates file named `example.cwl` unexpectedly

### ISSUE THREAD

**Issue by hexylena** [common-workflow-language/gxargparse#26]
Took me a few minutes to understand why my changes weren't sticking as I had created an `example.cwl` for testing.

When `example.py` is run, it outputs the CWL tool to both stdout + `example.cwl` (one also has an extra newline). This seems like odd behaviour to me (a linux admin). If it outputs to stdout, I don't expect it to also be writing to a file.

```
$ strace -e open python example.py --generate_cwl_tool 2>&1 | grep example.cwl
open("example.cwl", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
```

Additionally one of them has an extra newline at the end (stdout vs updated file).

**Comment by mr-c** [comment]
+1 Yes, it should either output to stdout out _or_ create a file using a specified name (but not some combination of both)
