### ISSUE TITLE
Open PR to add cnvkit wrappers to https://github.com/common-workflow-language/workflows

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/gxargparse#4]
It can be a "standing" or "[WIP]" (work in progress) pull request.

**Comment by anton-khodak** [comment]
Take a look at my initial attempt: https://github.com/common-workflow-language/gxargparse/tree/dev/test/cnvkit-tools . I didn't run them with actual arguments, so they might not work as expected.

**Comment by mr-c** [comment]
Can you make a pull request against the repo I mentioned? We have automated tests for wrappera that are run by Travis CI

**Comment by anton-khodak** [comment]
Nah, I understand now what is this issue for. I'll do it.

**Comment by anton-khodak** [comment]
Opened: https://github.com/common-workflow-language/workflows/pull/93

**Comment by mr-c** [comment]
Perfect, thanks!

On Tue, May 31, 2016 at 7:44 PM, Anton Khodak notifications@github.com
wrote:

> Closed #4
> https://github.com/common-workflow-language/gxargparse/issues/4.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/common-workflow-language/gxargparse/issues/4#event-677356785,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABROCLA-8SRCZKQUDT2RqddEHIgwRx_8ks5qHHNugaJpZM4IlNd3
> .

## 

Michael R. Crusoe
Community Engineer & Co-founder
Common Workflow Language project
https://impactstory.org/u/0000-0002-2961-9670
michael.crusoe@gmail.com
+32 (0) 2 808 25 58
+1 480 627 9108
